const errMessage = (method, target) =>
  `There was an problem while trying to ${method} the ${target}. Please try again.`;

export default errMessage;
